const countryCodes = [
  { code: '+1', name: 'USA' },
  { code: '+44', name: 'UK' },
  { code: '+91', name: 'India' },
  { code: '+61', name: 'Australia' },
  { code: '+81', name: 'Japan' },
  { code: '+33', name: 'France' },
  { code: '+49', name: 'Germany' },
  { code: '+55', name: 'Brazil' },
  { code: '+27', name: 'South Africa' },
  { code: '+39', name: 'Italy' },
  { code: '+34', name: 'Spain' },
  { code: '+7', name: 'Russia' },
  { code: '+86', name: 'China' },
  { code: '+82', name: 'South Korea' },
  { code: '+65', name: 'Singapore' },
  { code: '+60', name: 'Malaysia' },
  { code: '+63', name: 'Philippines' },
  { code: '+64', name: 'New Zealand' },
  { code: '+31', name: 'Netherlands' },
  { code: '+358', name: 'Finland' },
  { code: '+46', name: 'Sweden' },
  { code: '+47', name: 'Norway' },
  { code: '+48', name: 'Poland' },
  { code: '+62', name: 'Indonesia' },
  { code: '+52', name: 'Mexico' },
  { code: '+90', name: 'Turkey' },
  { code: '+41', name: 'Switzerland' },
  { code: '+66', name: 'Thailand' },
  { code: '+971', name: 'UAE' },
  { code: '+98', name: 'Iran' },
  { code: '+234', name: 'Nigeria' },
  { code: '+84', name: 'Vietnam' },
  { code: '+972', name: 'Israel' },
  { code: '+32', name: 'Belgium' },
  { code: '+20', name: 'Egypt' },
  { code: '+223', name: 'Mali' },
  { code: '+880', name: 'Bangladesh' },
  { code: '+36', name: 'Hungary' },
  { code: '+30', name: 'Greece' },
  { code: '+92', name: 'Pakistan' },
  { code: '+40', name: 'Romania' },
  { code: '+351', name: 'Portugal' },
  { code: '+94', name: 'Sri Lanka' },
  { code: '+58', name: 'Venezuela' },
  { code: '+56', name: 'Chile' },
  { code: '+93', name: 'Afghanistan' },
  { code: '+355', name: 'Albania' },
  { code: '+213', name: 'Algeria' },
  { code: '+54', name: 'Argentina' },
  { code: '+43', name: 'Austria' },
  { code: '+375', name: 'Belarus' },
  { code: '+501', name: 'Belize' },
  { code: '+387', name: 'Bosnia and Herzegovina' },
  { code: '+267', name: 'Botswana' },
  { code: '+673', name: 'Brunei' },
  { code: '+359', name: 'Bulgaria' },
  { code: '+855', name: 'Cambodia' },
  { code: '+237', name: 'Cameroon' },
  { code: '+1', name: 'Canada' },
  { code: '+238', name: 'Cape Verde' },
  { code: '+236', name: 'Central African Republic' },
  { code: '+235', name: 'Chad' },
  { code: '+57', name: 'Colombia' },
  { code: '+269', name: 'Comoros' },
  { code: '+506', name: 'Costa Rica' },
  { code: '+53', name: 'Cuba' },
  { code: '+420', name: 'Czech Republic' },
  { code: '+243', name: 'Democratic Republic of the Congo' },
  { code: '+45', name: 'Denmark' },
  { code: '+253', name: 'Djibouti' },
  { code: '+1', name: 'Dominica' },
  { code: '+809', name: 'Dominican Republic' },
  { code: '+593', name: 'Ecuador' },
  { code: '+503', name: 'El Salvador' },
  { code: '+240', name: 'Equatorial Guinea' },
  { code: '+291', name: 'Eritrea' },
  { code: '+372', name: 'Estonia' },
  { code: '+251', name: 'Ethiopia' },
  { code: '+679', name: 'Fiji' },
  { code: '+241', name: 'Gabon' },
  { code: '+220', name: 'Gambia' },
  { code: '+995', name: 'Georgia' },
  { code: '+233', name: 'Ghana' },
  { code: '+502', name: 'Guatemala' },
  { code: '+224', name: 'Guinea' },
  { code: '+245', name: 'Guinea-Bissau' },
  { code: '+592', name: 'Guyana' },
  { code: '+509', name: 'Haiti' },
  { code: '+504', name: 'Honduras' },
  { code: '+852', name: 'Hong Kong' },
  { code: '+354', name: 'Iceland' },
  { code: '+964', name: 'Iraq' },
  { code: '+353', name: 'Ireland' }
];

export default countryCodes;
