// ----------------------------------------------------------------------

export const fullName = [
  'Jayvion Simon',
  'Lucian Obrien',
  'Deja Brady',
  'Harrison Stein',
  'Reece Chung',
  'Lainey Davidson',
  'Cristopher Cardenas',
  'Melanie Noble',
  'Chase Day',
  'Shawn Manning',
  'Soren Durham',
  'Cortez Herring',
  'Brycen Jimenez',
  'Giana Brandt',
  'Aspen Schmitt',
  'Colten Aguilar',
  'Angelique Morse',
  'Selina Boyer',
  'Lawson Bass',
  'Ariana Lang',
  'Amiah Pruitt',
  'Harold Mcgrath',
  'Esperanza Mcintyre',
  'Mireya Conner',
  'Jamie Kline',
  'Laney Vazquez',
  'Tiffany May',
  'Dexter Shepherd',
  'Jaqueline Spencer',
  'Londyn Jarvis',
  'Yesenia Butler',
  'Jayvon Hull',
  'Izayah Pope',
  'Ayana Hunter',
  'Isabell Bender',
  'Desiree Schmidt',
  'Aidan Stout',
  'Jace Bush',
  'Janiya Williamson',
  'Hudson Alvarez'
];
export const status = [
  'Active',
  'Inactive',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Inactive'
];

export const firstName = [
  'Mossie',
  'David',
  'Ebba',
  'Chester',
  'Eula',
  'Jaren',
  'Boyd',
  'Brady',
  'Aida',
  'Anastasia',
  'Gregoria',
  'Julianne',
  'Ila',
  'Elyssa',
  'Lucio',
  'Lewis',
  'Jacinthe',
  'Molly',
  'Brown',
  'Fritz',
  'Keon',
  'Ella',
  'Ken',
  'Whitney',
  'Monte',
  'Rose',
  'Shana',
  'Devon',
  'Jaleel',
  'Laury',
  'Brooks',
  'Bruce',
  'Avery',
  'Esperanza',
  'Helene',
  'Heloise',
  'Elinor',
  'Adeline',
  'Haley',
  'Anabelle'
];

export const lastName = [
  'Carroll',
  'Simonis',
  'Yost',
  'Hand',
  'Emmerich',
  'Wilderman',
  'Howell',
  'Sporer',
  'Boehm',
  'Morar',
  'Koch',
  'Reynolds',
  'Padberg',
  'Watsica',
  'Upton',
  'Yundt',
  'Pfeffer',
  'Parker',
  'Zulauf',
  'Treutel',
  'McDermott',
  'McDermott',
  'Cruickshank',
  'Parisian',
  'Auer',
  'Turner',
  'Dooley',
  'Wiegand',
  'Abbott',
  'Wisoky',
  'Fahey',
  'Satterfield',
  'Bahringer',
  'Schulist',
  'Durgan',
  'Carroll',
  'Jones',
  'Leffler',
  'Gutkowski',
  'Homenick'
];

export const eventsTitle = [
  'Introduction of Gaura Ecosystem',
  'Digibot Project Presentation',
  'Gaura Ecosystem Dubai Event',
  'GAURA Ecosystem India Meetup',
  'Indonasia Community Meetup',
  'Digibot Launching Moments',
  'NFT Making Process'
];
export const eventsLink = [
  'https://www.youtube.com/watch?v=2Ixv7F5hRyc',
  'https://www.youtube.com/watch?v=ZysEarObrR0',
  'https://www.youtube.com/watch?v=uB4SC6jG7mw',
  'https://www.youtube.com/watch?v=HOeoE-wGoUc',
  'https://www.youtube.com/watch?v=d473_7IqJSY',
  'https://www.youtube.com/watch?v=YxaG1tv2yOw',
  'https://www.youtube.com/watch?v=d473_7IqJSY',
  'https://www.youtube.com/watch?v=iuYM7nGys0E'
];
export const eventsIMG = [
  '/thumbnail/maxresdefault.jpg',
  '/thumbnail/digibot-presentetion.jpg',
  '/thumbnail/dubai-event.jpg',
  '/thumbnail/india-event.jpg',
  '/thumbnail/indonasia-event.jpg',
  '/thumbnail/Digibot-lauching.jpg',
  '/thumbnail/efil-tower-design.jpg'
];

// ----------------------------------------------------------------------

export const email = [
  'nannie_abernathy70@yahoo.com',
  'ashlynn_ohara62@gmail.com',
  'milo.farrell@hotmail.com',
  'violet.ratke86@yahoo.com',
  'letha_lubowitz24@yahoo.com',
  'aditya_greenfelder31@gmail.com',
  'lenna_bergnaum27@hotmail.com',
  'luella.ryan33@gmail.com',
  'joana.simonis84@gmail.com',
  'marjolaine_white94@gmail.com',
  'vergie_block82@hotmail.com',
  'vito.hudson@hotmail.com',
  'tyrel_greenholt@gmail.com',
  'dwight.block85@yahoo.com',
  'mireya13@hotmail.com',
  'dasia_jenkins@hotmail.com',
  'benny89@yahoo.com',
  'dawn.goyette@gmail.com',
  'zella_hickle4@yahoo.com',
  'avery43@hotmail.com',
  'olen_legros@gmail.com',
  'jimmie.gerhold73@hotmail.com',
  'genevieve.powlowski@hotmail.com',
  'louie.kuphal39@gmail.com',
  'enoch.cruickshank@gmail.com',
  'arlo_mccullough@gmail.com',
  'sadie18@yahoo.com',
  'aric67@gmail.com',
  'mack_deckow53@gmail.com',
  'constantin91@yahoo.com',
  'lonny84@hotmail.com',
  'gus56@hotmail.com',
  'brennon64@yahoo.com',
  'hortense.streich@hotmail.com',
  'kallie_powlowski57@hotmail.com',
  'meghan.kemmer@hotmail.com',
  'bella.mraz14@yahoo.com',
  'barney88@gmail.com',
  'diamond_johns@hotmail.com',
  'gus80@hotmail.com'
];

export const reflink = [
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'https://digibot.co/digibotUApp/Signup?UplineId=3741529',
  'Full Stack Designer'
];

// ----------------------------------------------------------------------

export const role = [
  'UX Designer',
  'Full Stack Designer',
  'Backend Developer',
  'UX Designer',
  'UX Designer',
  'Project Manager',
  'Leader',
  'Backend Developer',
  'Project Manager',
  'UI Designer',
  'UI/UX Designer',
  'UI/UX Designer',
  'UI Designer',
  'Backend Developer',
  'Backend Developer',
  'Front End Developer',
  'Backend Developer',
  'Full Stack Designer',
  'Full Stack Developer',
  'Backend Developer',
  'UX Designer',
  'UI Designer',
  'Project Manager',
  'UI/UX Designer',
  'UI Designer',
  'Project Manager',
  'Full Stack Developer',
  'Hr Manager',
  'Hr Manager',
  'UI/UX Designer',
  'Project Manager',
  'Full Stack Designer',
  'UI Designer',
  'Leader',
  'Front End Developer',
  'UI/UX Designer',
  'Project Manager',
  'UI/UX Designer',
  'UI Designer',
  'Full Stack Designer'
];

export const stoneHold = [
  '',
  'The Space Stone',
  'The Space Stone',
  'The Space Stone',
  'The Mind Stone',
  'The Mind Stone',
  'The Mind Stone',
  'The Reality Stone',
  'The Reality Stone',
  'The Reality Stone',
  'The Reality Stone',
  'The Power Stone',
  'The Power Stone',
  'The Power Stone',
  'The Power Stone',
  'The Time Stone',
  'The Soul Stone',
  'The Aveneger Stone'
];

export const positions = [
  'Member',
  'Agent',
  'Manager',
  'General Manager',
  'Meta Trainer',
  'Meta Educational Manager',
  'Regional Manager',
  'Chief Development officer',
  'Chief Marketing Officer',
  'Chief Technical Officer',
  'Chief Operating Officer',
  'Area Head',
  'Zonal Head',
  'Country Head',
  'Global VP',
  'The Time Stone',
  'The Soul Stone',
  'The Avenger'
];

export const teamBusiness = [
  '0 USD',
  '125 USD',
  '250 USD',
  '600 USD',
  '1,250 USD',
  '1,600 USD',
  '2,000 USD',
  '3,000 USD',
  '5,000 USD',
  '7,500 USD',
  '11,000 USD',
  '25,000 USD',
  '35,000 USD',
  '55,000 USD',
  '1,50,000 USD',
  '3,50,000 USD',
  '7,00,000 USD',
  '25,00,000 USD'
];
